---
- hosts: all
  become: yes
   
  tasks:
  - name: install pip3
    apt: name=python3-pip 
     state=present

  - name: install modules
    pip:
        state: present
        name: "{{ modules }}"
    vars:
        modules:
          - pyopenssl

  - name: Create a directory if it does not exist
    ansible.builtin.file:
        path: /etc/ssl/
        owner: ubuntu 
        group: ubuntu 
        mode: 0755
        state: directory

  vars:
    - server_hostname: internetexplorer.com
    - key_size: 4096
    - passphrase: # Set if you want passphrase
    - key_type: DSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
    - country_name: US
    - email_address: admin@internetexplorer.com
    - organization_name: internetexplorer

      tasks:
    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: /etc/ssl/certs/{{ server_hostname }}_privkey.pem
        size: "{{ key_size }}"
        type: "{{ key_type }}"
        backup: yes

    - name: Generate an OpenSSL Certificate Signing Request with Subject information
      openssl_csr:
        path: "/etc/ssl/certs/{{ server_hostname }}.csr"
        privatekey_path: "/etc/ssl/certs/{{ server_hostname }}_privkey.pem"
        country_name: "{{ country_name }}"
        organization_name: "{{ organization_name }}"
        email_address: "{{ email_address }}"
        common_name: "{{ server_hostname }}"

    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: "./certificates/{{ server_hostname }}_cert.pem"
        privatekey_path: "/etc/ssl/certs/{{ server_hostname }}_privkey.pem"
        csr_path: "/etc/ssl/certs/{{ server_hostname }}.csr"
        provider: selfsigned

        tasks:
    #- name: Install Python Package Manager
     # apt:
     #  pkg:
     #  - python3-pip

   # - name: Install pyOpenSSL package
    #  pip:
     #   name: pyOpenSSL



  
   