---
  - name: Create node_exporter user
    user:
      name: node_exporter
      state: present
      shell: /bin/bash
      system: no 
      createhome: yes
    become_user: root
  - name: Unarchive a file that needs to be downloaded
    unarchive:
      src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
      dest: /home/ubuntu
      remote_src: yes
  - name: Copy file
    copy:
      src: /home/ubuntu/node_exporter-1.0.1.linux-amd64/node_exporter
      dest: /usr/local/bin/
  - name: Change file permission
    file:
      path: /usr/local/bin/node_exporter
      owner: node_exporter
      group: node_exporter
      mode: '755'
  - name: Delete unwanted files
    file:
      state: absent
      path: /home/ubuntu/node_exporter-1.0.1.linux-amd64.tar.gz
  - name: Delete unwanted files
    file:
      state: absent
      path: /home/ubuntu/node_exporter-1.0.1.linux-amd64
  - name: Copy file
    copy:
      src: /home/ubuntu/roles/node_exporter/files/node_exporter.service
      dest: /etc/systemd/system/node_exporter.service
  - name: Start node_exporter
    systemd:
    state: started
    name: node_exporter
    daemon_reload: yes
    enabled: yes
  - name: Copy file
    copy:
      src: /home/ubuntu/roles/node_exporter/files/prometheus2.yml
      dest: /etc/prometheus/prometheus.yml
  - name: Restart Prometheus
    systemd:
    name: prometheus
    state: restarted